// <auto-generated />
using System;
using Backend.Database;
using Backend.Domain.Enum;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260401044521_ProperOneToOneUserRelation")]
    partial class ProperOneToOneUserRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "issue_type", new[] { "bug", "investigation", "story", "task" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Backend.Domain.Entity.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommentaryId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("CommentaryId")
                        .IsUnique()
                        .HasDatabaseName("IX__Attachment__CommentaryId");

                    b.ToTable("Attachment", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entity.Column", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Column", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entity.ColumnRelation", b =>
                {
                    b.Property<Guid>("PrevColumnId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NextColumnId")
                        .HasColumnType("uuid");

                    b.HasKey("PrevColumnId", "NextColumnId");

                    b.HasIndex("NextColumnId");

                    b.HasIndex("PrevColumnId", "NextColumnId")
                        .IsUnique()
                        .HasDatabaseName("IX__ColumnRelation__PrevNextColumns");

                    b.ToTable("ColumnRelation", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entity.Commentary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsDescription")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("IssueId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastEditedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId")
                        .IsUnique()
                        .HasDatabaseName("IX__Commentary__AuthorId");

                    b.HasIndex("IssueId")
                        .IsUnique()
                        .HasDatabaseName("IX__Commentary__IssueId");

                    b.ToTable("Commentary", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entity.Issue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssigneeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ColumnId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<IssueType>("IssueType")
                        .HasColumnType("issue_type");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("StoryPoints")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId")
                        .IsUnique()
                        .HasDatabaseName("IX__Issue__AssigneeId");

                    b.HasIndex("AuthorId")
                        .IsUnique()
                        .HasDatabaseName("IX__Issue__AuthorId");

                    b.HasIndex("ColumnId");

                    b.ToTable("Issue", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entity.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId")
                        .IsUnique()
                        .HasDatabaseName("IX__Project__CreatorId");

                    b.HasIndex("TeamId")
                        .IsUnique()
                        .HasDatabaseName("IX__Project__TeamId");

                    b.ToTable("Project", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entity.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.ToTable("Team", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entity.TeamUserProfile", b =>
                {
                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("TeamId", "UserProfileId", "RoleId");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("IX__TeamUserProfile__RoleId");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("IX__TeamUserProfile__TeamId");

                    b.HasIndex("UserProfileId")
                        .HasDatabaseName("IX__TeamUserProfile__UserProfileId");

                    b.HasIndex("TeamId", "UserProfileId")
                        .IsUnique()
                        .HasDatabaseName("IX__TeamUserProfile__TeamUserProfileUnique");

                    b.ToTable("TeamUserProfile", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX__User__Email");

                    b.HasIndex("UserProfileId")
                        .IsUnique()
                        .HasDatabaseName("IX__User__UserProfileId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entity.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Avatar")
                        .IsRequired()
                        .HasMaxLength(5242880)
                        .HasColumnType("bytea");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("FirstName", "SecondName")
                        .IsUnique()
                        .HasDatabaseName("IX__UserProfile__FullName");

                    b.ToTable("UserProfile", (string)null);
                });

            modelBuilder.Entity("Backend.Domain.Entity.Attachment", b =>
                {
                    b.HasOne("Backend.Domain.Entity.Commentary", "Commentary")
                        .WithMany("Attachments")
                        .HasForeignKey("CommentaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commentary");
                });

            modelBuilder.Entity("Backend.Domain.Entity.Column", b =>
                {
                    b.HasOne("Backend.Domain.Entity.Project", "Project")
                        .WithMany("Columns")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Backend.Domain.Entity.ColumnRelation", b =>
                {
                    b.HasOne("Backend.Domain.Entity.Column", "NextColumn")
                        .WithMany("PrevColumnRelations")
                        .HasForeignKey("NextColumnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Domain.Entity.Column", "PrevColumn")
                        .WithMany("NextColumnRelations")
                        .HasForeignKey("PrevColumnId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NextColumn");

                    b.Navigation("PrevColumn");
                });

            modelBuilder.Entity("Backend.Domain.Entity.Commentary", b =>
                {
                    b.HasOne("Backend.Domain.Entity.UserProfile", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Backend.Domain.Entity.Issue", "Issue")
                        .WithMany("Commentaries")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("Backend.Domain.Entity.Issue", b =>
                {
                    b.HasOne("Backend.Domain.Entity.UserProfile", "Assignee")
                        .WithMany()
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Backend.Domain.Entity.UserProfile", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Backend.Domain.Entity.Column", "Column")
                        .WithMany("Issues")
                        .HasForeignKey("ColumnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignee");

                    b.Navigation("Author");

                    b.Navigation("Column");
                });

            modelBuilder.Entity("Backend.Domain.Entity.Project", b =>
                {
                    b.HasOne("Backend.Domain.Entity.UserProfile", "Creator")
                        .WithMany("Projects")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Domain.Entity.Team", "Team")
                        .WithMany("Projects")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Backend.Domain.Entity.Role", b =>
                {
                    b.HasOne("Backend.Domain.Entity.Team", "Team")
                        .WithMany("Roles")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Backend.Domain.Entity.TeamUserProfile", b =>
                {
                    b.HasOne("Backend.Domain.Entity.Role", "Role")
                        .WithMany("TeamUserProfiles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Domain.Entity.Team", "Team")
                        .WithMany("TeamUserProfiles")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Domain.Entity.UserProfile", "UserProfile")
                        .WithMany("TeamUserProfiles")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Team");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Backend.Domain.Entity.User", b =>
                {
                    b.HasOne("Backend.Domain.Entity.UserProfile", "UserProfile")
                        .WithOne("User")
                        .HasForeignKey("Backend.Domain.Entity.User", "UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Backend.Domain.Entity.Column", b =>
                {
                    b.Navigation("Issues");

                    b.Navigation("NextColumnRelations");

                    b.Navigation("PrevColumnRelations");
                });

            modelBuilder.Entity("Backend.Domain.Entity.Commentary", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("Backend.Domain.Entity.Issue", b =>
                {
                    b.Navigation("Commentaries");
                });

            modelBuilder.Entity("Backend.Domain.Entity.Project", b =>
                {
                    b.Navigation("Columns");
                });

            modelBuilder.Entity("Backend.Domain.Entity.Role", b =>
                {
                    b.Navigation("TeamUserProfiles");
                });

            modelBuilder.Entity("Backend.Domain.Entity.Team", b =>
                {
                    b.Navigation("Projects");

                    b.Navigation("Roles");

                    b.Navigation("TeamUserProfiles");
                });

            modelBuilder.Entity("Backend.Domain.Entity.UserProfile", b =>
                {
                    b.Navigation("Projects");

                    b.Navigation("TeamUserProfiles");

                    b.Navigation("User")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
